import {
  FaRocket,
  FaEye,
  FaCode,
  FaShieldAlt,
  FaNetworkWired,
  FaUsers,
  FaTools,
  FaCheck,
  FaCoins,
  FaChartLine,
  FaHandshake,
  FaGavel,
  FaWallet,
  FaVoteYea,
  FaFileContract,
  FaLock,
  FaGlobe,
  FaCube,
  FaLayerGroup,
  FaCheckCircle,
  FaArrowRight,
  FaHospital,
  FaTruck,
  FaHome,
  FaGamepad,
  FaUniversity,
  FaBolt,
  FaGraduationCap,
  FaPaintBrush,
  FaCogs,
  FaBullhorn,
  FaEyeSlash,
  FaKey,
  FaSearch,
  FaLink,
  FaUserShield,
  FaCloudUploadAlt,
  FaHeadset,
  FaBrain,
  FaPuzzlePiece,
  FaInfinity,
  FaTrophy,
  FaBuilding,
  FaDollarSign,
  FaExclamationTriangle,
} from "react-icons/fa";
import { IconType } from "react-icons";

// Map icon names to actual icon components
export const iconMap: Record<string, IconType> = {
  FaRocket,
  FaEye,
  FaCode,
  FaShieldAlt,
  FaNetworkWired,
  FaUsers,
  FaTools,
  FaCheck,
  FaCoins,
  FaChartLine,
  FaHandshake,
  FaGavel,
  FaWallet,
  FaVoteYea,
  FaFileContract,
  FaLock,
  FaGlobe,
  FaCube,
  FaLayerGroup,
  FaCheckCircle,
  FaArrowRight,
  FaHospital,
  FaTruck,
  FaHome,
  FaGamepad,
  FaUniversity,
  FaBolt,
  FaGraduationCap,
  FaPaintBrush,
  FaCogs,
  FaBullhorn,
  FaEyeSlash,
  FaKey,
  FaSearch,
  FaLink,
  FaUserShield,
  FaCloudUploadAlt,
  FaHeadset,
  FaBrain,
  FaPuzzlePiece,
  FaInfinity,
  FaTrophy,
  FaBuilding,
  FaDollarSign,
  FaExclamationTriangle,
};

// Get icon component by name
export function getIcon(iconName: string): IconType {
  return iconMap[iconName] || FaCode; // Default to FaCode if not found
}
